config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'dashboard/index', as: 'dashboard'

  post 'dashboard/generate_new_token',
    to: 'dashboard#generate_new_token',
    as: 'generate_new_token'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :downloads, only: [:index]

      get 'downloads/latest', to: 'downloads#latest'

      resources :taxon_concepts, only: [:index] do
        resources :cites_legislation, only: [:index]
        resources :distributions, only: [:index]
        resources :eu_legislation, only: [:index]
        resources :references, only: [:index]
      end
    end

    get 'test_exception_notifier', controller: :base, action: :test_exception_notifier
  end

  devise_for :users, :controllers => { registrations: "registrations" }

  apipie

  match 'nomenclature' => 'static_pages#nomenclature', via: [:get]

  mount Sidekiq::Web => '/sidekiq'

  root 'static_pages#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :get_stats

  def index
  end

  def generate_new_token
    current_user.generate_authentication_token
    redirect_to dashboard_url, notice: "New token generated successfully!"
  end

  private
  def get_stats
    @all_users_successful_requests = current_user.api_requests.where(response_status: 200)
    @all_users_unsuccessful_requests = current_user.api_requests.where(response_status: 500)
    @users_last_30_days_requests = current_user.api_requests.order(
      :response_status
    ).group(
      :response_status
    ).group_by_day(
      :created_at,
      range: 30.days.ago.midnight..Time.now
    ).count
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  # Take the hash necessary for the line graph and replace 200 with 'Successful'
  # and anything else with 'Failed' and return newly constructed hash
  def sanitise_hash_for_line_graph(hash)
    new_hash = {}
    hash.map { |k,v| 
      n = k[0] == 200 ? 'Successful' : 'Failed'
      new_hash[[n, k[1]]] = v 
    }
    new_hash
  end
end

app/views/dashboard/index.html.erb
<h1>API Token for <%= current_user.email %></h1>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h4><%= current_user.authentication_token.present? ? current_user.authentication_token : "You need to generate a token first" %>  <small><%= link_to 'Generate New Token', generate_new_token_path, method: :post, class: 'btn btn-success', id: 'generate-new-token' %></small></h4>
      </div>
    </div>
  </div>
</div>

<h1>Last 30 Days Activity</h1>
<div class="row">
  <div class="col-lg-12">
    <% if current_user.api_requests.any? %>
      <%= line_chart sanitise_hash_for_line_graph(@users_last_30_days_requests), library: { 
          title: 'Requests by HTTP Status', 
          titlePosition: 'out',
          colors: ['#4AC948', '#EE3B3B']
        } %>
    <% else %>
      <h4>You have not yet made any API requests</h4>
    <% end %>
  </div>
</div>

<h1>Total Activity (All Time)</h1>
<% if current_user.api_requests.any? %>
  <div class="row">
    <div class="col-lg-6">
      <h4>Successful Requests to Date</h4>
      <h1><%= number_with_delimiter(@all_users_successful_requests.count, :delimiter => ',')
       %></h1>
    </div>
    <div class="col-lg-6">
      <h4>Unsuccessful Requests to Date</h4>
      <h1><%= number_with_delimiter(@all_users_unsuccessful_requests.count, :delimiter => ',')
       %></h1>
    </div>
  </div>
<% else %>
  <h4>You have not yet made any API requests</h4>
<% end %>